[package]
name = "masp_mpc"
version = "0.2.0"
authors = ["Sean Bowe <ewillbefull@gmail.com>", "joe <joe@cryptium.ch>"]
edition = "2018"

[lib]
crate-type = ["lib",]

[[bin]]
name = "new"
required-features = ["verification"]

[[bin]]
name = "verify"
required-features = ["verification"]

[[bin]]
name = "beacon"
required-features = ["beacon"]

[[bin]]
name = "verify_transform"

[[bin]]
name = "split_params"

[dependencies]
rand = "0.4"
blake2 = "0.9"
bellman = { version = "0.8", default-features = false, features = ["groth16"] }
ff = "0.8" 
bls12_381 = "0.3"
exitcode = "1.1.2"
hex = "0.4.2"
itertools = "0.9"
num-bigint = "0.3"
num-traits = "0.2.12"
byteorder = "1"
sha2 = "0.9"
blake2s_simd = "0.5"

[dependencies.bellman_ce]
git = "https://github.com/metastatedev/phase2-bls12_381"
branch = "main"

[dependencies.phase2]
git = "https://github.com/metastatedev/phase2-bls12_381"
branch = "main"

[dependencies.pairing]
git = "https://github.com/metastatedev/phase2-bls12_381"
package = "pairing_ce"
branch = "main"

[dependencies.masp_proofs]
git = "https://github.com/metastatedev/librustzcash"
rev = "b64af55d955a1bd0a77389f0b9c66f180815e73b"
optional = true

[dependencies.hex-literal]
version = "0.1"
optional = true

[features]
verification = ["masp_proofs"]
#u128-support = ["pairing/u128-support"]
beacon = ["hex-literal"]
